"""Verified starter catalog: federal act identifiers and official URLs."""

CATALOG = [
    {"slug":"13709-2018","law_type":"Lei","number":"13.709","year":2018,"title":"Lei Geral de Proteção de Dados Pessoais","aliases":["LGPD","lei geral de dados","lei de proteção de dados","proteção de dados"],"description":"Dispõe sobre o tratamento de dados pessoais, inclusive nos meios digitais.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/L13709compilado.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/L13709compilado.htm"},
    {"slug":"12965-2014","law_type":"Lei","number":"12.965","year":2014,"title":"Marco Civil da Internet","aliases":["MCI","lei da internet","marco civil"],"description":"Estabelece princípios, garantias, direitos e deveres para o uso da Internet no Brasil.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2014/lei/l12965.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2014/lei/l12965.htm"},
    {"slug":"11340-2006","law_type":"Lei","number":"11.340","year":2006,"title":"Lei Maria da Penha","aliases":["Maria da Penha","lei de violência doméstica","violência contra a mulher"],"description":"Cria mecanismos para coibir a violência doméstica e familiar contra a mulher.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11340.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11340.htm"},
    {"slug":"8078-1990","law_type":"Lei","number":"8.078","year":1990,"title":"Código de Defesa do Consumidor","aliases":["CDC","código do consumidor","defesa do consumidor"],"description":"Dispõe sobre a proteção do consumidor e dá outras providências.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/leis/L8078compilado.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/leis/L8078compilado.htm"},
    {"slug":"8069-1990","law_type":"Lei","number":"8.069","year":1990,"title":"Estatuto da Criança e do Adolescente","aliases":["ECA","estatuto da criança","lei da infância"],"description":"Dispõe sobre o Estatuto da Criança e do Adolescente.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/leis/L8069compilado.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/leis/L8069compilado.htm"},
    {"slug":"14133-2021","law_type":"Lei","number":"14.133","year":2021,"title":"Lei de Licitações e Contratos Administrativos","aliases":["nova lei de licitações","lei 14133","licitações"],"description":"Estabelece normas gerais de licitação e contratação para as Administrações Públicas.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/L14133.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/L14133.htm"},
    {"slug":"8429-1992","law_type":"Lei","number":"8.429","year":1992,"title":"Lei de Improbidade Administrativa","aliases":["LIA","lei da improbidade","improbidade administrativa"],"description":"Dispõe sobre as sanções aplicáveis em virtude da prática de atos de improbidade administrativa.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/leis/L8429compilada.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/leis/L8429compilada.htm"},
    {"slug":"lcp-135-2010","law_type":"Lei Complementar","number":"135","year":2010,"title":"Lei da Ficha Limpa","aliases":["Ficha Limpa","Lei Complementar 135","LC 135/2010"],"description":"Altera a Lei Complementar nº 64, de 1990, para estabelecer hipóteses de inelegibilidade.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp135.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/leis/lcp/lcp135.htm"},
    {"slug":"constituicao-1988","law_type":"Constituição","number":"1988","year":1988,"title":"Constituição da República Federativa do Brasil","aliases":["Constituição Federal","CF","CF/88","Constituição"],"description":"Constituição da República Federativa do Brasil, promulgada em 5 de outubro de 1988.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/constituicao/ConstituicaoCompilado.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/constituicao/ConstituicaoCompilado.htm"},
    {"slug":"10406-2002","law_type":"Lei","number":"10.406","year":2002,"title":"Código Civil","aliases":["CC","código civil brasileiro"],"description":"Institui o Código Civil.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/leis/2002/L10406compilada.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/leis/2002/L10406compilada.htm"},
    {"slug":"2848-1940","law_type":"Decreto-Lei","number":"2.848","year":1940,"title":"Código Penal","aliases":["CP","código penal brasileiro"],"description":"Código Penal brasileiro.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/decreto-lei/Del2848compilado.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/decreto-lei/Del2848compilado.htm"},
    {"slug":"5172-1966","law_type":"Lei","number":"5.172","year":1966,"title":"Código Tributário Nacional","aliases":["CTN","código tributário"],"description":"Dispõe sobre o Sistema Tributário Nacional e institui normas gerais de direito tributário aplicáveis à União, Estados e Municípios.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/leis/L5172compilado.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/leis/L5172compilado.htm"},
    {"slug":"5452-1943","law_type":"Decreto-Lei","number":"5.452","year":1943,"title":"Consolidação das Leis do Trabalho","aliases":["CLT","leis trabalhistas"],"description":"Aprova a Consolidação das Leis do Trabalho.","published_at":None,"hot":True,"source_url":"https://www.planalto.gov.br/ccivil_03/decreto-lei/Del5452compilado.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/decreto-lei/Del5452compilado.htm"},
    {"slug":"12527-2011","law_type":"Lei","number":"12.527","year":2011,"title":"Lei de Acesso à Informação","aliases":["LAI","lei de acesso a informação","lei da transparência"],"description":"Regula o acesso a informações previsto na Constituição Federal.","published_at":None,"hot":False,"source_url":"https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm","fetch_url":"http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm"},
]

AMENDING_LAWS = {
    ("14.550", 2023): {
        "label": "Lei nº 14.550/2023",
        "source_url": "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/L14550.htm",
        "fetch_url": "http://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/L14550.htm",
        "changed_at": "2023-04-19",
    }
}
